import type { EmojiData } from "../../types/emojis";

export const activities: EmojiData["activities"] = [
  
    { n: ["jack-o-lantern", "jack o lantern"], u: "1f383" },
    { n: ["christmas tree"], u: "1f384" },
    { n: ["fireworks"], u: "1f386" },
    { n: ["sparkler", "firework sparkler"], u: "1f387" },
    { n: ["firecracker"], u: "1f9e8" },
    { n: ["sparkles"], u: "2728" },
    { n: ["balloon"], u: "1f388" },
    { n: ["tada", "party popper"], u: "1f389" },
    { n: ["confetti ball"], u: "1f38a" },
    { n: ["tanabata tree"], u: "1f38b" },
    { n: ["bamboo", "pine decoration"], u: "1f38d" },
    { n: ["dolls", "japanese dolls"], u: "1f38e" },
    { n: ["flags", "carp streamer"], u: "1f38f" },
    { n: ["wind chime"], u: "1f390" },
    { n: ["rice scene", "moon viewing ceremony"], u: "1f391" },
    { n: ["red envelope", "red gift envelope"], u: "1f9e7" },
    { n: ["ribbon"], u: "1f380" },
    { n: ["gift", "wrapped present"], u: "1f381" },
    { n: ["reminder ribbon"], u: "1f397-fe0f" },
    { n: ["admission tickets"], u: "1f39f-fe0f" },
    { n: ["ticket"], u: "1f3ab" },
    { n: ["medal", "military medal"], u: "1f396-fe0f" },
    { n: ["trophy"], u: "1f3c6" },
    { n: ["sports medal"], u: "1f3c5" },
    { n: ["first place medal"], u: "1f947" },
    { n: ["second place medal"], u: "1f948" },
    { n: ["third place medal"], u: "1f949" },
    { n: ["soccer", "soccer ball"], u: "26bd" },
    { n: ["baseball"], u: "26be" },
    { n: ["softball"], u: "1f94e" },
    { n: ["basketball", "basketball and hoop"], u: "1f3c0" },
    { n: ["volleyball"], u: "1f3d0" },
    { n: ["football", "american football"], u: "1f3c8" },
    { n: ["rugby football"], u: "1f3c9" },
    { n: ["tennis", "tennis racquet and ball"], u: "1f3be" },
    { n: ["flying disc"], u: "1f94f" },
    { n: ["bowling"], u: "1f3b3" },
    { n: ["cricket bat and ball"], u: "1f3cf" },
    { n: ["field hockey stick and ball"], u: "1f3d1" },
    { n: ["ice hockey stick and puck"], u: "1f3d2" },
    { n: ["lacrosse", "lacrosse stick and ball"], u: "1f94d" },
    { n: ["table tennis paddle and ball"], u: "1f3d3" },
    { n: ["badminton racquet and shuttlecock"], u: "1f3f8" },
    { n: ["boxing glove"], u: "1f94a" },
    { n: ["martial arts uniform"], u: "1f94b" },
    { n: ["goal net"], u: "1f945" },
    { n: ["golf", "flag in hole"], u: "26f3" },
    { n: ["ice skate"], u: "26f8-fe0f" },
    { n: ["fishing pole and fish"], u: "1f3a3" },
    { n: ["diving mask"], u: "1f93f" },
    { n: ["running shirt with sash"], u: "1f3bd" },
    { n: ["ski", "ski and ski boot"], u: "1f3bf" },
    { n: ["sled"], u: "1f6f7" },
    { n: ["curling stone"], u: "1f94c" },
    { n: ["dart", "direct hit"], u: "1f3af" },
    { n: ["yo-yo"], u: "1fa80" },
    { n: ["kite"], u: "1fa81" },
    { n: ["8ball", "billiards"], u: "1f3b1" },
    { n: ["crystal ball"], u: "1f52e" },
    { n: ["magic wand"], u: "1fa84" },
    { n: ["nazar amulet"], u: "1f9ff" },
    { n: ["hamsa"], u: "1faac" },
    { n: ["video game"], u: "1f3ae" },
    { n: ["joystick"], u: "1f579-fe0f" },
    { n: ["slot machine"], u: "1f3b0" },
    { n: ["game die"], u: "1f3b2" },
    { n: ["jigsaw", "jigsaw puzzle piece"], u: "1f9e9" },
    { n: ["teddy bear"], u: "1f9f8" },
    { n: ["pinata"], u: "1fa85" },
    { n: ["mirror ball"], u: "1faa9" },
    { n: ["nesting dolls"], u: "1fa86" },
    { n: ["spades", "black spade suit"], u: "2660-fe0f" },
    { n: ["hearts", "black heart suit"], u: "2665-fe0f" },
    { n: ["diamonds", "black diamond suit"], u: "2666-fe0f" },
    { n: ["clubs", "black club suit"], u: "2663-fe0f" },
    { n: ["chess pawn"], u: "265f-fe0f" },
    { n: ["black joker", "playing card black joker"], u: "1f0cf" },
    { n: ["mahjong", "mahjong tile red dragon"], u: "1f004" },
    { n: ["flower playing cards"], u: "1f3b4" },
    { n: ["performing arts"], u: "1f3ad" },
    { n: ["framed picture", "frame with picture"], u: "1f5bc-fe0f" },
    { n: ["art", "artist palette"], u: "1f3a8" },
    { n: ["thread", "spool of thread"], u: "1f9f5" },
    { n: ["sewing needle"], u: "1faa1" },
    { n: ["yarn", "ball of yarn"], u: "1f9f6" },
    { n: ["knot"], u: "1faa2" },
  ];
