import type { EmojiData } from "../../types/emojis";

export const animals_nature: EmojiData["animals_nature"] = [
  
    { n: ["monkey face"], u: "1f435" },
    { n: ["monkey"], u: "1f412" },
    { n: ["gorilla"], u: "1f98d" },
    { n: ["orangutan"], u: "1f9a7" },
    { n: ["dog", "dog face"], u: "1f436" },
    { n: ["dog", "dog2"], u: "1f415" },
    { n: ["guide dog"], u: "1f9ae" },
    { n: ["service dog"], u: "1f415-200d-1f9ba" },
    { n: ["poodle"], u: "1f429" },
    { n: ["wolf", "wolf face"], u: "1f43a" },
    { n: ["fox face"], u: "1f98a" },
    { n: ["raccoon"], u: "1f99d" },
    { n: ["cat", "cat face"], u: "1f431" },
    { n: ["cat", "cat2"], u: "1f408" },
    { n: ["black cat"], u: "1f408-200d-2b1b" },
    { n: ["lion face"], u: "1f981" },
    { n: ["tiger", "tiger face"], u: "1f42f" },
    { n: ["tiger", "tiger2"], u: "1f405" },
    { n: ["leopard"], u: "1f406" },
    { n: ["horse", "horse face"], u: "1f434" },
    { n: ["horse", "racehorse"], u: "1f40e" },
    { n: ["unicorn face"], u: "1f984" },
    { n: ["zebra face"], u: "1f993" },
    { n: ["deer"], u: "1f98c" },
    { n: ["bison"], u: "1f9ac" },
    { n: ["cow", "cow face"], u: "1f42e" },
    { n: ["ox"], u: "1f402" },
    { n: ["water buffalo"], u: "1f403" },
    { n: ["cow", "cow2"], u: "1f404" },
    { n: ["pig", "pig face"], u: "1f437" },
    { n: ["pig", "pig2"], u: "1f416" },
    { n: ["boar"], u: "1f417" },
    { n: ["pig nose"], u: "1f43d" },
    { n: ["ram"], u: "1f40f" },
    { n: ["sheep"], u: "1f411" },
    { n: ["goat"], u: "1f410" },
    { n: ["dromedary camel"], u: "1f42a" },
    { n: ["camel", "bactrian camel"], u: "1f42b" },
    { n: ["llama"], u: "1f999" },
    { n: ["giraffe face"], u: "1f992" },
    { n: ["elephant"], u: "1f418" },
    { n: ["mammoth"], u: "1f9a3" },
    { n: ["rhinoceros"], u: "1f98f" },
    { n: ["hippopotamus"], u: "1f99b" },
    { n: ["mouse", "mouse face"], u: "1f42d" },
    { n: ["mouse", "mouse2"], u: "1f401" },
    { n: ["rat"], u: "1f400" },
    { n: ["hamster", "hamster face"], u: "1f439" },
    { n: ["rabbit", "rabbit face"], u: "1f430" },
    { n: ["rabbit", "rabbit2"], u: "1f407" },
    { n: ["chipmunk"], u: "1f43f-fe0f" },
    { n: ["beaver"], u: "1f9ab" },
    { n: ["hedgehog"], u: "1f994" },
    { n: ["bat"], u: "1f987" },
    { n: ["bear", "bear face"], u: "1f43b" },
    { n: ["polar bear"], u: "1f43b-200d-2744-fe0f" },
    { n: ["koala"], u: "1f428" },
    { n: ["panda face"], u: "1f43c" },
    { n: ["sloth"], u: "1f9a5" },
    { n: ["otter"], u: "1f9a6" },
    { n: ["skunk"], u: "1f9a8" },
    { n: ["kangaroo"], u: "1f998" },
    { n: ["badger"], u: "1f9a1" },
    { n: ["feet", "paw prints"], u: "1f43e" },
    { n: ["turkey"], u: "1f983" },
    { n: ["chicken"], u: "1f414" },
    { n: ["rooster"], u: "1f413" },
    { n: ["hatching chick"], u: "1f423" },
    { n: ["baby chick"], u: "1f424" },
    { n: ["hatched chick", "front-facing baby chick"], u: "1f425" },
    { n: ["bird"], u: "1f426" },
    { n: ["penguin"], u: "1f427" },
    { n: ["dove", "dove of peace"], u: "1f54a-fe0f" },
    { n: ["eagle"], u: "1f985" },
    { n: ["duck"], u: "1f986" },
    { n: ["swan"], u: "1f9a2" },
    { n: ["owl"], u: "1f989" },
    { n: ["dodo"], u: "1f9a4" },
    { n: ["feather"], u: "1fab6" },
    { n: ["flamingo"], u: "1f9a9" },
    { n: ["peacock"], u: "1f99a" },
    { n: ["parrot"], u: "1f99c" },
    { n: ["frog", "frog face"], u: "1f438" },
    { n: ["crocodile"], u: "1f40a" },
    { n: ["turtle"], u: "1f422" },
    { n: ["lizard"], u: "1f98e" },
    { n: ["snake"], u: "1f40d" },
    { n: ["dragon face"], u: "1f432" },
    { n: ["dragon"], u: "1f409" },
    { n: ["sauropod"], u: "1f995" },
    { n: ["t-rex"], u: "1f996" },
    { n: ["whale", "spouting whale"], u: "1f433" },
    { n: ["whale", "whale2"], u: "1f40b" },
    { n: ["dolphin", "flipper"], u: "1f42c" },
    { n: ["seal"], u: "1f9ad" },
    { n: ["fish"], u: "1f41f" },
    { n: ["tropical fish"], u: "1f420" },
    { n: ["blowfish"], u: "1f421" },
    { n: ["shark"], u: "1f988" },
    { n: ["octopus"], u: "1f419" },
    { n: ["shell", "spiral shell"], u: "1f41a" },
    { n: ["coral"], u: "1fab8" },
    { n: ["snail"], u: "1f40c" },
    { n: ["butterfly"], u: "1f98b" },
    { n: ["bug"], u: "1f41b" },
    { n: ["ant"], u: "1f41c" },
    { n: ["bee", "honeybee"], u: "1f41d" },
    { n: ["beetle"], u: "1fab2" },
    { n: ["ladybug", "lady beetle"], u: "1f41e" },
    { n: ["cricket"], u: "1f997" },
    { n: ["cockroach"], u: "1fab3" },
    { n: ["spider"], u: "1f577-fe0f" },
    { n: ["spider web"], u: "1f578-fe0f" },
    { n: ["scorpion"], u: "1f982" },
    { n: ["mosquito"], u: "1f99f" },
    { n: ["fly"], u: "1fab0" },
    { n: ["worm"], u: "1fab1" },
    { n: ["microbe"], u: "1f9a0" },
    { n: ["bouquet"], u: "1f490" },
    { n: ["cherry blossom"], u: "1f338" },
    { n: ["white flower"], u: "1f4ae" },
    { n: ["lotus"], u: "1fab7" },
    { n: ["rosette"], u: "1f3f5-fe0f" },
    { n: ["rose"], u: "1f339" },
    { n: ["wilted flower"], u: "1f940" },
    { n: ["hibiscus"], u: "1f33a" },
    { n: ["sunflower"], u: "1f33b" },
    { n: ["blossom"], u: "1f33c" },
    { n: ["tulip"], u: "1f337" },
    { n: ["seedling"], u: "1f331" },
    { n: ["potted plant"], u: "1fab4" },
    { n: ["evergreen tree"], u: "1f332" },
    { n: ["deciduous tree"], u: "1f333" },
    { n: ["palm tree"], u: "1f334" },
    { n: ["cactus"], u: "1f335" },
    { n: ["ear of rice"], u: "1f33e" },
    { n: ["herb"], u: "1f33f" },
    { n: ["shamrock"], u: "2618-fe0f" },
    { n: ["four leaf clover"], u: "1f340" },
    { n: ["maple leaf"], u: "1f341" },
    { n: ["fallen leaf"], u: "1f342" },
    { n: ["leaves", "leaf fluttering in wind"], u: "1f343" },
    { n: ["empty nest"], u: "1fab9" },
    { n: ["nest with eggs"], u: "1faba" },
  ],
};
