import type { EmojiData } from "../../types/emojis";

export const flags: EmojiData["flags"] = [
  
    { n: ["chequered flag", "checkered flag"], u: "1f3c1" },
    { n: ["triangular flag on post"], u: "1f6a9" },
    { n: ["crossed flags"], u: "1f38c" },
    { n: ["waving black flag"], u: "1f3f4" },
    { n: ["white flag", "waving white flag"], u: "1f3f3-fe0f" },
    { n: ["rainbow flag", "rainbow-flag"], u: "1f3f3-fe0f-200d-1f308" },
    { n: ["transgender flag"], u: "1f3f3-fe0f-200d-26a7-fe0f" },
    { n: ["pirate flag"], u: "1f3f4-200d-2620-fe0f" },
    { n: ["flag-ac", "ascension island flag"], u: "1f1e6-1f1e8" },
    { n: ["flag-ad", "andorra flag"], u: "1f1e6-1f1e9" },
    { n: ["flag-ae", "united arab emirates flag"], u: "1f1e6-1f1ea" },
    { n: ["flag-af", "afghanistan flag"], u: "1f1e6-1f1eb" },
    { n: ["flag-ag", "antigua & barbuda flag"], u: "1f1e6-1f1ec" },
    { n: ["flag-ai", "anguilla flag"], u: "1f1e6-1f1ee" },
    { n: ["flag-al", "albania flag"], u: "1f1e6-1f1f1" },
    { n: ["flag-am", "armenia flag"], u: "1f1e6-1f1f2" },
    { n: ["flag-ao", "angola flag"], u: "1f1e6-1f1f4" },
    { n: ["flag-aq", "antarctica flag"], u: "1f1e6-1f1f6" },
    { n: ["flag-ar", "argentina flag"], u: "1f1e6-1f1f7" },
    { n: ["flag-as", "american samoa flag"], u: "1f1e6-1f1f8" },
    { n: ["flag-at", "austria flag"], u: "1f1e6-1f1f9" },
    { n: ["flag-au", "australia flag"], u: "1f1e6-1f1fa" },
    { n: ["flag-aw", "aruba flag"], u: "1f1e6-1f1fc" },
    { n: ["flag-ax", "åland islands flag"], u: "1f1e6-1f1fd" },
    { n: ["flag-az", "azerbaijan flag"], u: "1f1e6-1f1ff" },
    { n: ["flag-ba", "bosnia & herzegovina flag"], u: "1f1e7-1f1e6" },
    { n: ["flag-bb", "barbados flag"], u: "1f1e7-1f1e7" },
    { n: ["flag-bd", "bangladesh flag"], u: "1f1e7-1f1e9" },
    { n: ["flag-be", "belgium flag"], u: "1f1e7-1f1ea" },
    { n: ["flag-bf", "burkina faso flag"], u: "1f1e7-1f1eb" },
    { n: ["flag-bg", "bulgaria flag"], u: "1f1e7-1f1ec" },
    { n: ["flag-bh", "bahrain flag"], u: "1f1e7-1f1ed" },
    { n: ["flag-bi", "burundi flag"], u: "1f1e7-1f1ee" },
    { n: ["flag-bj", "benin flag"], u: "1f1e7-1f1ef" },
    { n: ["flag-bl", "st. barthélemy flag"], u: "1f1e7-1f1f1" },
    { n: ["flag-bm", "bermuda flag"], u: "1f1e7-1f1f2" },
    { n: ["flag-bn", "brunei flag"], u: "1f1e7-1f1f3" },
    { n: ["flag-bo", "bolivia flag"], u: "1f1e7-1f1f4" },
    { n: ["flag-bq", "caribbean netherlands flag"], u: "1f1e7-1f1f6" },
    { n: ["flag-br", "brazil flag"], u: "1f1e7-1f1f7" },
    { n: ["flag-bs", "bahamas flag"], u: "1f1e7-1f1f8" },
    { n: ["flag-bt", "bhutan flag"], u: "1f1e7-1f1f9" },
    { n: ["flag-bv", "bouvet island flag"], u: "1f1e7-1f1fb" },
    { n: ["flag-bw", "botswana flag"], u: "1f1e7-1f1fc" },
    { n: ["flag-by", "belarus flag"], u: "1f1e7-1f1fe" },
    { n: ["flag-bz", "belize flag"], u: "1f1e7-1f1ff" },
    { n: ["flag-ca", "canada flag"], u: "1f1e8-1f1e6" },
    { n: ["flag-cc", "cocos (keeling) islands flag"], u: "1f1e8-1f1e8" },
    { n: ["flag-cd", "congo - kinshasa flag"], u: "1f1e8-1f1e9" },
    { n: ["flag-cf", "central african republic flag"], u: "1f1e8-1f1eb" },
    { n: ["flag-cg", "congo - brazzaville flag"], u: "1f1e8-1f1ec" },
    { n: ["flag-ch", "switzerland flag"], u: "1f1e8-1f1ed" },
    { n: ["flag-ci", "côte d’ivoire flag"], u: "1f1e8-1f1ee" },
    { n: ["flag-ck", "cook islands flag"], u: "1f1e8-1f1f0" },
    { n: ["flag-cl", "chile flag"], u: "1f1e8-1f1f1" },
    { n: ["flag-cm", "cameroon flag"], u: "1f1e8-1f1f2" },
    { n: ["cn", "flag-cn", "china flag"], u: "1f1e8-1f1f3" },
    { n: ["flag-co", "colombia flag"], u: "1f1e8-1f1f4" },
    { n: ["flag-cp", "clipperton island flag"], u: "1f1e8-1f1f5" },
    { n: ["flag-cr", "costa rica flag"], u: "1f1e8-1f1f7" },
    { n: ["flag-cu", "cuba flag"], u: "1f1e8-1f1fa" },
    { n: ["flag-cv", "cape verde flag"], u: "1f1e8-1f1fb" },
    { n: ["flag-cw", "curaçao flag"], u: "1f1e8-1f1fc" },
    { n: ["flag-cx", "christmas island flag"], u: "1f1e8-1f1fd" },
    { n: ["flag-cy", "cyprus flag"], u: "1f1e8-1f1fe" },
    { n: ["flag-cz", "czechia flag"], u: "1f1e8-1f1ff" },
    { n: ["de", "flag-de", "germany flag"], u: "1f1e9-1f1ea" },
    { n: ["flag-dg", "diego garcia flag"], u: "1f1e9-1f1ec" },
    { n: ["flag-dj", "djibouti flag"], u: "1f1e9-1f1ef" },
    { n: ["flag-dk", "denmark flag"], u: "1f1e9-1f1f0" },
    { n: ["flag-dm", "dominica flag"], u: "1f1e9-1f1f2" },
    { n: ["flag-do", "dominican republic flag"], u: "1f1e9-1f1f4" },
    { n: ["flag-dz", "algeria flag"], u: "1f1e9-1f1ff" },
    { n: ["flag-ea", "ceuta & melilla flag"], u: "1f1ea-1f1e6" },
    { n: ["flag-ec", "ecuador flag"], u: "1f1ea-1f1e8" },
    { n: ["flag-ee", "estonia flag"], u: "1f1ea-1f1ea" },
    { n: ["flag-eg", "egypt flag"], u: "1f1ea-1f1ec" },
    { n: ["flag-eh", "western sahara flag"], u: "1f1ea-1f1ed" },
    { n: ["flag-er", "eritrea flag"], u: "1f1ea-1f1f7" },
    { n: ["es", "flag-es", "spain flag"], u: "1f1ea-1f1f8" },
    { n: ["flag-et", "ethiopia flag"], u: "1f1ea-1f1f9" },
    { n: ["flag-eu", "european union flag"], u: "1f1ea-1f1fa" },
    { n: ["flag-fi", "finland flag"], u: "1f1eb-1f1ee" },
    { n: ["flag-fj", "fiji flag"], u: "1f1eb-1f1ef" },
    { n: ["flag-fk", "falkland islands flag"], u: "1f1eb-1f1f0" },
    { n: ["flag-fm", "micronesia flag"], u: "1f1eb-1f1f2" },
    { n: ["flag-fo", "faroe islands flag"], u: "1f1eb-1f1f4" },
    { n: ["fr", "flag-fr", "france flag"], u: "1f1eb-1f1f7" },
    { n: ["flag-ga", "gabon flag"], u: "1f1ec-1f1e6" },
    { n: ["gb", "uk", "flag-gb", "united kingdom flag"], u: "1f1ec-1f1e7" },
    { n: ["flag-gd", "grenada flag"], u: "1f1ec-1f1e9" },
    { n: ["flag-ge", "georgia flag"], u: "1f1ec-1f1ea" },
    { n: ["flag-gf", "french guiana flag"], u: "1f1ec-1f1eb" },
    { n: ["flag-gg", "guernsey flag"], u: "1f1ec-1f1ec" },
    { n: ["flag-gh", "ghana flag"], u: "1f1ec-1f1ed" },
    { n: ["flag-gi", "gibraltar flag"], u: "1f1ec-1f1ee" },
    { n: ["flag-gl", "greenland flag"], u: "1f1ec-1f1f1" },
    { n: ["flag-gm", "gambia flag"], u: "1f1ec-1f1f2" },
    { n: ["flag-gn", "guinea flag"], u: "1f1ec-1f1f3" },
    { n: ["flag-gp", "guadeloupe flag"], u: "1f1ec-1f1f5" },
    { n: ["flag-gq", "equatorial guinea flag"], u: "1f1ec-1f1f6" },
    { n: ["flag-gr", "greece flag"], u: "1f1ec-1f1f7" },
    {
      n: ["flag-gs", "south georgia & south sandwich islands flag"],
      u: "1f1ec-1f1f8",
    },
    { n: ["flag-gt", "guatemala flag"], u: "1f1ec-1f1f9" },
    { n: ["flag-gu", "guam flag"], u: "1f1ec-1f1fa" },
    { n: ["flag-gw", "guinea-bissau flag"], u: "1f1ec-1f1fc" },
    { n: ["flag-gy", "guyana flag"], u: "1f1ec-1f1fe" },
    { n: ["flag-hk", "hong kong sar china flag"], u: "1f1ed-1f1f0" },
    { n: ["flag-hm", "heard & mcdonald islands flag"], u: "1f1ed-1f1f2" },
    { n: ["flag-hn", "honduras flag"], u: "1f1ed-1f1f3" },
    { n: ["flag-hr", "croatia flag"], u: "1f1ed-1f1f7" },
    { n: ["flag-ht", "haiti flag"], u: "1f1ed-1f1f9" },
    { n: ["flag-hu", "hungary flag"], u: "1f1ed-1f1fa" },
    { n: ["flag-ic", "canary islands flag"], u: "1f1ee-1f1e8" },
    { n: ["flag-id", "indonesia flag"], u: "1f1ee-1f1e9" },
    { n: ["flag-ie", "ireland flag"], u: "1f1ee-1f1ea" },
    { n: ["flag-il", "israel flag"], u: "1f1ee-1f1f1" },
    { n: ["flag-im", "isle of man flag"], u: "1f1ee-1f1f2" },
    { n: ["flag-in", "india flag"], u: "1f1ee-1f1f3" },
    { n: ["flag-io", "british indian ocean territory flag"], u: "1f1ee-1f1f4" },
    { n: ["flag-iq", "iraq flag"], u: "1f1ee-1f1f6" },
    { n: ["flag-ir", "iran flag"], u: "1f1ee-1f1f7" },
    { n: ["flag-is", "iceland flag"], u: "1f1ee-1f1f8" },
    { n: ["it", "flag-it", "italy flag"], u: "1f1ee-1f1f9" },
    { n: ["flag-je", "jersey flag"], u: "1f1ef-1f1ea" },
    { n: ["flag-jm", "jamaica flag"], u: "1f1ef-1f1f2" },
    { n: ["flag-jo", "jordan flag"], u: "1f1ef-1f1f4" },
    { n: ["jp", "flag-jp", "japan flag"], u: "1f1ef-1f1f5" },
    { n: ["flag-ke", "kenya flag"], u: "1f1f0-1f1ea" },
    { n: ["flag-kg", "kyrgyzstan flag"], u: "1f1f0-1f1ec" },
    { n: ["flag-kh", "cambodia flag"], u: "1f1f0-1f1ed" },
    { n: ["flag-ki", "kiribati flag"], u: "1f1f0-1f1ee" },
    { n: ["flag-km", "comoros flag"], u: "1f1f0-1f1f2" },
    { n: ["flag-kn", "st. kitts & nevis flag"], u: "1f1f0-1f1f3" },
    { n: ["flag-kp", "north korea flag"], u: "1f1f0-1f1f5" },
    { n: ["kr", "flag-kr", "south korea flag"], u: "1f1f0-1f1f7" },
    { n: ["flag-kw", "kuwait flag"], u: "1f1f0-1f1fc" },
    { n: ["flag-ky", "cayman islands flag"], u: "1f1f0-1f1fe" },
    { n: ["flag-kz", "kazakhstan flag"], u: "1f1f0-1f1ff" },
    { n: ["flag-la", "laos flag"], u: "1f1f1-1f1e6" },
    { n: ["flag-lb", "lebanon flag"], u: "1f1f1-1f1e7" },
    { n: ["flag-lc", "st. lucia flag"], u: "1f1f1-1f1e8" },
    { n: ["flag-li", "liechtenstein flag"], u: "1f1f1-1f1ee" },
    { n: ["flag-lk", "sri lanka flag"], u: "1f1f1-1f1f0" },
    { n: ["flag-lr", "liberia flag"], u: "1f1f1-1f1f7" },
    { n: ["flag-ls", "lesotho flag"], u: "1f1f1-1f1f8" },
    { n: ["flag-lt", "lithuania flag"], u: "1f1f1-1f1f9" },
    { n: ["flag-lu", "luxembourg flag"], u: "1f1f1-1f1fa" },
    { n: ["flag-lv", "latvia flag"], u: "1f1f1-1f1fb" },
    { n: ["flag-ly", "libya flag"], u: "1f1f1-1f1fe" },
    { n: ["flag-ma", "morocco flag"], u: "1f1f2-1f1e6" },
    { n: ["flag-mc", "monaco flag"], u: "1f1f2-1f1e8" },
    { n: ["flag-md", "moldova flag"], u: "1f1f2-1f1e9" },
    { n: ["flag-me", "montenegro flag"], u: "1f1f2-1f1ea" },
    { n: ["flag-mf", "st. martin flag"], u: "1f1f2-1f1eb" },
    { n: ["flag-mg", "madagascar flag"], u: "1f1f2-1f1ec" },
    { n: ["flag-mh", "marshall islands flag"], u: "1f1f2-1f1ed" },
    { n: ["flag-mk", "north macedonia flag"], u: "1f1f2-1f1f0" },
    { n: ["flag-ml", "mali flag"], u: "1f1f2-1f1f1" },
    { n: ["flag-mm", "myanmar (burma) flag"], u: "1f1f2-1f1f2" },
    { n: ["flag-mn", "mongolia flag"], u: "1f1f2-1f1f3" },
    { n: ["flag-mo", "macao sar china flag"], u: "1f1f2-1f1f4" },
    { n: ["flag-mp", "northern mariana islands flag"], u: "1f1f2-1f1f5" },
    { n: ["flag-mq", "martinique flag"], u: "1f1f2-1f1f6" },
    { n: ["flag-mr", "mauritania flag"], u: "1f1f2-1f1f7" },
    { n: ["flag-ms", "montserrat flag"], u: "1f1f2-1f1f8" },
    { n: ["flag-mt", "malta flag"], u: "1f1f2-1f1f9" },
    { n: ["flag-mu", "mauritius flag"], u: "1f1f2-1f1fa" },
    { n: ["flag-mv", "maldives flag"], u: "1f1f2-1f1fb" },
    { n: ["flag-mw", "malawi flag"], u: "1f1f2-1f1fc" },
    { n: ["flag-mx", "mexico flag"], u: "1f1f2-1f1fd" },
    { n: ["flag-my", "malaysia flag"], u: "1f1f2-1f1fe" },
    { n: ["flag-mz", "mozambique flag"], u: "1f1f2-1f1ff" },
    { n: ["flag-na", "namibia flag"], u: "1f1f3-1f1e6" },
    { n: ["flag-nc", "new caledonia flag"], u: "1f1f3-1f1e8" },
    { n: ["flag-ne", "niger flag"], u: "1f1f3-1f1ea" },
    { n: ["flag-nf", "norfolk island flag"], u: "1f1f3-1f1eb" },
    { n: ["flag-ng", "nigeria flag"], u: "1f1f3-1f1ec" },
    { n: ["flag-ni", "nicaragua flag"], u: "1f1f3-1f1ee" },
    { n: ["flag-nl", "netherlands flag"], u: "1f1f3-1f1f1" },
    { n: ["flag-no", "norway flag"], u: "1f1f3-1f1f4" },
    { n: ["flag-np", "nepal flag"], u: "1f1f3-1f1f5" },
    { n: ["flag-nr", "nauru flag"], u: "1f1f3-1f1f7" },
    { n: ["flag-nu", "niue flag"], u: "1f1f3-1f1fa" },
    { n: ["flag-nz", "new zealand flag"], u: "1f1f3-1f1ff" },
    { n: ["flag-om", "oman flag"], u: "1f1f4-1f1f2" },
    { n: ["flag-pa", "panama flag"], u: "1f1f5-1f1e6" },
    { n: ["flag-pe", "peru flag"], u: "1f1f5-1f1ea" },
    { n: ["flag-pf", "french polynesia flag"], u: "1f1f5-1f1eb" },
    { n: ["flag-pg", "papua new guinea flag"], u: "1f1f5-1f1ec" },
    { n: ["flag-ph", "philippines flag"], u: "1f1f5-1f1ed" },
    { n: ["flag-pk", "pakistan flag"], u: "1f1f5-1f1f0" },
    { n: ["flag-pl", "poland flag"], u: "1f1f5-1f1f1" },
    { n: ["flag-pm", "st. pierre & miquelon flag"], u: "1f1f5-1f1f2" },
    { n: ["flag-pn", "pitcairn islands flag"], u: "1f1f5-1f1f3" },
    { n: ["flag-pr", "puerto rico flag"], u: "1f1f5-1f1f7" },
    { n: ["flag-ps", "palestinian territories flag"], u: "1f1f5-1f1f8" },
    { n: ["flag-pt", "portugal flag"], u: "1f1f5-1f1f9" },
    { n: ["flag-pw", "palau flag"], u: "1f1f5-1f1fc" },
    { n: ["flag-py", "paraguay flag"], u: "1f1f5-1f1fe" },
    { n: ["flag-qa", "qatar flag"], u: "1f1f6-1f1e6" },
    { n: ["flag-re", "réunion flag"], u: "1f1f7-1f1ea" },
    { n: ["flag-ro", "romania flag"], u: "1f1f7-1f1f4" },
    { n: ["flag-rs", "serbia flag"], u: "1f1f7-1f1f8" },
    { n: ["ru", "flag-ru", "russia flag"], u: "1f1f7-1f1fa" },
    { n: ["flag-rw", "rwanda flag"], u: "1f1f7-1f1fc" },
    { n: ["flag-sa", "saudi arabia flag"], u: "1f1f8-1f1e6" },
    { n: ["flag-sb", "solomon islands flag"], u: "1f1f8-1f1e7" },
    { n: ["flag-sc", "seychelles flag"], u: "1f1f8-1f1e8" },
    { n: ["flag-sd", "sudan flag"], u: "1f1f8-1f1e9" },
    { n: ["flag-se", "sweden flag"], u: "1f1f8-1f1ea" },
    { n: ["flag-sg", "singapore flag"], u: "1f1f8-1f1ec" },
    { n: ["flag-sh", "st. helena flag"], u: "1f1f8-1f1ed" },
    { n: ["flag-si", "slovenia flag"], u: "1f1f8-1f1ee" },
    { n: ["flag-sj", "svalbard & jan mayen flag"], u: "1f1f8-1f1ef" },
    { n: ["flag-sk", "slovakia flag"], u: "1f1f8-1f1f0" },
    { n: ["flag-sl", "sierra leone flag"], u: "1f1f8-1f1f1" },
    { n: ["flag-sm", "san marino flag"], u: "1f1f8-1f1f2" },
    { n: ["flag-sn", "senegal flag"], u: "1f1f8-1f1f3" },
    { n: ["flag-so", "somalia flag"], u: "1f1f8-1f1f4" },
    { n: ["flag-sr", "suriname flag"], u: "1f1f8-1f1f7" },
    { n: ["flag-ss", "south sudan flag"], u: "1f1f8-1f1f8" },
    { n: ["flag-st", "são tomé & príncipe flag"], u: "1f1f8-1f1f9" },
    { n: ["flag-sv", "el salvador flag"], u: "1f1f8-1f1fb" },
    { n: ["flag-sx", "sint maarten flag"], u: "1f1f8-1f1fd" },
    { n: ["flag-sy", "syria flag"], u: "1f1f8-1f1fe" },
    { n: ["flag-sz", "eswatini flag"], u: "1f1f8-1f1ff" },
    { n: ["flag-ta", "tristan da cunha flag"], u: "1f1f9-1f1e6" },
    { n: ["flag-tc", "turks & caicos islands flag"], u: "1f1f9-1f1e8" },
    { n: ["flag-td", "chad flag"], u: "1f1f9-1f1e9" },
    { n: ["flag-tf", "french southern territories flag"], u: "1f1f9-1f1eb" },
    { n: ["flag-tg", "togo flag"], u: "1f1f9-1f1ec" },
    { n: ["flag-th", "thailand flag"], u: "1f1f9-1f1ed" },
    { n: ["flag-tj", "tajikistan flag"], u: "1f1f9-1f1ef" },
    { n: ["flag-tk", "tokelau flag"], u: "1f1f9-1f1f0" },
    { n: ["flag-tl", "timor-leste flag"], u: "1f1f9-1f1f1" },
    { n: ["flag-tm", "turkmenistan flag"], u: "1f1f9-1f1f2" },
    { n: ["flag-tn", "tunisia flag"], u: "1f1f9-1f1f3" },
    { n: ["flag-to", "tonga flag"], u: "1f1f9-1f1f4" },
    { n: ["flag-tr", "turkey flag"], u: "1f1f9-1f1f7" },
    { n: ["flag-tt", "trinidad & tobago flag"], u: "1f1f9-1f1f9" },
    { n: ["flag-tv", "tuvalu flag"], u: "1f1f9-1f1fb" },
    { n: ["flag-tw", "taiwan flag"], u: "1f1f9-1f1fc" },
    { n: ["flag-tz", "tanzania flag"], u: "1f1f9-1f1ff" },
    { n: ["flag-ua", "ukraine flag"], u: "1f1fa-1f1e6" },
    { n: ["flag-ug", "uganda flag"], u: "1f1fa-1f1ec" },
    { n: ["flag-um", "u.s. outlying islands flag"], u: "1f1fa-1f1f2" },
    { n: ["flag-un", "united nations flag"], u: "1f1fa-1f1f3" },
    { n: ["us", "flag-us", "united states flag"], u: "1f1fa-1f1f8" },
    { n: ["flag-uy", "uruguay flag"], u: "1f1fa-1f1fe" },
    { n: ["flag-uz", "uzbekistan flag"], u: "1f1fa-1f1ff" },
    { n: ["flag-va", "vatican city flag"], u: "1f1fb-1f1e6" },
    { n: ["flag-vc", "st. vincent & grenadines flag"], u: "1f1fb-1f1e8" },
    { n: ["flag-ve", "venezuela flag"], u: "1f1fb-1f1ea" },
    { n: ["flag-vg", "british virgin islands flag"], u: "1f1fb-1f1ec" },
    { n: ["flag-vi", "u.s. virgin islands flag"], u: "1f1fb-1f1ee" },
    { n: ["flag-vn", "vietnam flag"], u: "1f1fb-1f1f3" },
    { n: ["flag-vu", "vanuatu flag"], u: "1f1fb-1f1fa" },
    { n: ["flag-wf", "wallis & futuna flag"], u: "1f1fc-1f1eb" },
    { n: ["flag-ws", "samoa flag"], u: "1f1fc-1f1f8" },
    { n: ["flag-xk", "kosovo flag"], u: "1f1fd-1f1f0" },
    { n: ["flag-ye", "yemen flag"], u: "1f1fe-1f1ea" },
    { n: ["flag-yt", "mayotte flag"], u: "1f1fe-1f1f9" },
    { n: ["flag-za", "south africa flag"], u: "1f1ff-1f1e6" },
    { n: ["flag-zm", "zambia flag"], u: "1f1ff-1f1f2" },
    { n: ["flag-zw", "zimbabwe flag"], u: "1f1ff-1f1fc" },
    {
      n: ["england flag", "flag-england"],
      u: "1f3f4-e0067-e0062-e0065-e006e-e0067-e007f",
    },
    {
      n: ["scotland flag", "flag-scotland"],
      u: "1f3f4-e0067-e0062-e0073-e0063-e0074-e007f",
    },
    {
      n: ["wales flag", "flag-wales"],
      u: "1f3f4-e0067-e0062-e0077-e006c-e0073-e007f",
    },
  ],
} as EmojiData;
];
