import type { EmojiData } from "../../types/emojis";

export const food_drink: EmojiData["food_drink"] = [
  
    { n: ["grapes"], u: "1f347" },
    { n: ["melon"], u: "1f348" },
    { n: ["watermelon"], u: "1f349" },
    { n: ["tangerine"], u: "1f34a" },
    { n: ["lemon"], u: "1f34b" },
    { n: ["banana"], u: "1f34c" },
    { n: ["pineapple"], u: "1f34d" },
    { n: ["mango"], u: "1f96d" },
    { n: ["apple", "red apple"], u: "1f34e" },
    { n: ["green apple"], u: "1f34f" },
    { n: ["pear"], u: "1f350" },
    { n: ["peach"], u: "1f351" },
    { n: ["cherries"], u: "1f352" },
    { n: ["strawberry"], u: "1f353" },
    { n: ["blueberries"], u: "1fad0" },
    { n: ["kiwifruit"], u: "1f95d" },
    { n: ["tomato"], u: "1f345" },
    { n: ["olive"], u: "1fad2" },
    { n: ["coconut"], u: "1f965" },
    { n: ["avocado"], u: "1f951" },
    { n: ["eggplant", "aubergine"], u: "1f346" },
    { n: ["potato"], u: "1f954" },
    { n: ["carrot"], u: "1f955" },
    { n: ["corn", "ear of maize"], u: "1f33d" },
    { n: ["hot pepper"], u: "1f336-fe0f" },
    { n: ["bell pepper"], u: "1fad1" },
    { n: ["cucumber"], u: "1f952" },
    { n: ["leafy green"], u: "1f96c" },
    { n: ["broccoli"], u: "1f966" },
    { n: ["garlic"], u: "1f9c4" },
    { n: ["onion"], u: "1f9c5" },
    { n: ["mushroom"], u: "1f344" },
    { n: ["peanuts"], u: "1f95c" },
    { n: ["beans"], u: "1fad8" },
    { n: ["chestnut"], u: "1f330" },
    { n: ["bread"], u: "1f35e" },
    { n: ["croissant"], u: "1f950" },
    { n: ["baguette bread"], u: "1f956" },
    { n: ["flatbread"], u: "1fad3" },
    { n: ["pretzel"], u: "1f968" },
    { n: ["bagel"], u: "1f96f" },
    { n: ["pancakes"], u: "1f95e" },
    { n: ["waffle"], u: "1f9c7" },
    { n: ["cheese wedge"], u: "1f9c0" },
    { n: ["meat on bone"], u: "1f356" },
    { n: ["poultry leg"], u: "1f357" },
    { n: ["cut of meat"], u: "1f969" },
    { n: ["bacon"], u: "1f953" },
    { n: ["hamburger"], u: "1f354" },
    { n: ["fries", "french fries"], u: "1f35f" },
    { n: ["pizza", "slice of pizza"], u: "1f355" },
    { n: ["hotdog", "hot dog"], u: "1f32d" },
    { n: ["sandwich"], u: "1f96a" },
    { n: ["taco"], u: "1f32e" },
    { n: ["burrito"], u: "1f32f" },
    { n: ["tamale"], u: "1fad4" },
    { n: ["stuffed flatbread"], u: "1f959" },
    { n: ["falafel"], u: "1f9c6" },
    { n: ["egg"], u: "1f95a" },
    { n: ["cooking", "fried egg"], u: "1f373" },
    { n: ["shallow pan of food"], u: "1f958" },
    { n: ["stew", "pot of food"], u: "1f372" },
    { n: ["fondue"], u: "1fad5" },
    { n: ["bowl with spoon"], u: "1f963" },
    { n: ["green salad"], u: "1f957" },
    { n: ["popcorn"], u: "1f37f" },
    { n: ["butter"], u: "1f9c8" },
    { n: ["salt", "salt shaker"], u: "1f9c2" },
    { n: ["canned food"], u: "1f96b" },
    { n: ["bento", "bento box"], u: "1f371" },
    { n: ["rice cracker"], u: "1f358" },
    { n: ["rice ball"], u: "1f359" },
    { n: ["rice", "cooked rice"], u: "1f35a" },
    { n: ["curry", "curry and rice"], u: "1f35b" },
    { n: ["ramen", "steaming bowl"], u: "1f35c" },
    { n: ["spaghetti"], u: "1f35d" },
    { n: ["sweet potato", "roasted sweet potato"], u: "1f360" },
    { n: ["oden"], u: "1f362" },
    { n: ["sushi"], u: "1f363" },
    { n: ["fried shrimp"], u: "1f364" },
    { n: ["fish cake", "fish cake with swirl design"], u: "1f365" },
    { n: ["moon cake"], u: "1f96e" },
    { n: ["dango"], u: "1f361" },
    { n: ["dumpling"], u: "1f95f" },
    { n: ["fortune cookie"], u: "1f960" },
    { n: ["takeout box"], u: "1f961" },
    { n: ["crab"], u: "1f980" },
    { n: ["lobster"], u: "1f99e" },
    { n: ["shrimp"], u: "1f990" },
    { n: ["squid"], u: "1f991" },
    { n: ["oyster"], u: "1f9aa" },
    { n: ["icecream", "soft ice cream"], u: "1f366" },
    { n: ["shaved ice"], u: "1f367" },
    { n: ["ice cream"], u: "1f368" },
    { n: ["doughnut"], u: "1f369" },
    { n: ["cookie"], u: "1f36a" },
    { n: ["birthday", "birthday cake"], u: "1f382" },
    { n: ["cake", "shortcake"], u: "1f370" },
    { n: ["cupcake"], u: "1f9c1" },
    { n: ["pie"], u: "1f967" },
    { n: ["chocolate bar"], u: "1f36b" },
    { n: ["candy"], u: "1f36c" },
    { n: ["lollipop"], u: "1f36d" },
    { n: ["custard"], u: "1f36e" },
    { n: ["honey pot"], u: "1f36f" },
    { n: ["baby bottle"], u: "1f37c" },
    { n: ["glass of milk"], u: "1f95b" },
    { n: ["coffee", "hot beverage"], u: "2615" },
    { n: ["teapot"], u: "1fad6" },
    { n: ["tea", "teacup without handle"], u: "1f375" },
    { n: ["sake", "sake bottle and cup"], u: "1f376" },
    { n: ["champagne", "bottle with popping cork"], u: "1f37e" },
    { n: ["wine glass"], u: "1f377" },
    { n: ["cocktail", "cocktail glass"], u: "1f378" },
    { n: ["tropical drink"], u: "1f379" },
    { n: ["beer", "beer mug"], u: "1f37a" },
    { n: ["beers", "clinking beer mugs"], u: "1f37b" },
    { n: ["clinking glasses"], u: "1f942" },
    { n: ["tumbler glass"], u: "1f943" },
    { n: ["pouring liquid"], u: "1fad7" },
    { n: ["cup with straw"], u: "1f964" },
    { n: ["bubble tea"], u: "1f9cb" },
    { n: ["beverage box"], u: "1f9c3" },
    { n: ["mate drink"], u: "1f9c9" },
    { n: ["ice cube"], u: "1f9ca" },
    { n: ["chopsticks"], u: "1f962" },
    { n: ["knife fork plate", "fork and knife with plate"], u: "1f37d-fe0f" },
    { n: ["fork and knife"], u: "1f374" },
    { n: ["spoon"], u: "1f944" },
    { n: ["hocho", "knife"], u: "1f52a" },
    { n: ["jar"], u: "1fad9" },
    { n: ["amphora"], u: "1f3fa" },
  ],
];
