import type { EmojiData } from "../../types/emojis";

export const objects: EmojiData["objects"] = [
  
    { n: ["eyeglasses"], u: "1f453" },
    { n: ["sunglasses", "dark sunglasses"], u: "1f576-fe0f" },
    { n: ["goggles"], u: "1f97d" },
    { n: ["lab coat"], u: "1f97c" },
    { n: ["safety vest"], u: "1f9ba" },
    { n: ["necktie"], u: "1f454" },
    { n: ["shirt", "tshirt", "t-shirt"], u: "1f455" },
    { n: ["jeans"], u: "1f456" },
    { n: ["scarf"], u: "1f9e3" },
    { n: ["gloves"], u: "1f9e4" },
    { n: ["coat"], u: "1f9e5" },
    { n: ["socks"], u: "1f9e6" },
    { n: ["dress"], u: "1f457" },
    { n: ["kimono"], u: "1f458" },
    { n: ["sari"], u: "1f97b" },
    { n: ["one-piece swimsuit"], u: "1fa71" },
    { n: ["briefs"], u: "1fa72" },
    { n: ["shorts"], u: "1fa73" },
    { n: ["bikini"], u: "1f459" },
    { n: ["womans clothes"], u: "1f45a" },
    { n: ["purse"], u: "1f45b" },
    { n: ["handbag"], u: "1f45c" },
    { n: ["pouch"], u: "1f45d" },
    { n: ["shopping bags"], u: "1f6cd-fe0f" },
    { n: ["school satchel"], u: "1f392" },
    { n: ["thong sandal"], u: "1fa74" },
    { n: ["shoe", "mans shoe"], u: "1f45e" },
    { n: ["athletic shoe"], u: "1f45f" },
    { n: ["hiking boot"], u: "1f97e" },
    { n: ["flat shoe", "womans flat shoe"], u: "1f97f" },
    { n: ["high heel", "high-heeled shoe"], u: "1f460" },
    { n: ["sandal", "womans sandal"], u: "1f461" },
    { n: ["ballet shoes"], u: "1fa70" },
    { n: ["boot", "womans boots"], u: "1f462" },
    { n: ["crown"], u: "1f451" },
    { n: ["womans hat"], u: "1f452" },
    { n: ["tophat", "top hat"], u: "1f3a9" },
    { n: ["mortar board", "graduation cap"], u: "1f393" },
    { n: ["billed cap"], u: "1f9e2" },
    { n: ["military helmet"], u: "1fa96" },
    {
      n: ["rescue worker’s helmet", "helmet with white cross"],
      u: "26d1-fe0f",
    },
    { n: ["prayer beads"], u: "1f4ff" },
    { n: ["lipstick"], u: "1f484" },
    { n: ["ring"], u: "1f48d" },
    { n: ["gem", "gem stone"], u: "1f48e" },
    { n: ["mute", "speaker with cancellation stroke"], u: "1f507" },
    { n: ["speaker"], u: "1f508" },
    { n: ["sound", "speaker with one sound wave"], u: "1f509" },
    { n: ["loud sound", "speaker with three sound waves"], u: "1f50a" },
    { n: ["loudspeaker", "public address loudspeaker"], u: "1f4e2" },
    { n: ["mega", "cheering megaphone"], u: "1f4e3" },
    { n: ["postal horn"], u: "1f4ef" },
    { n: ["bell"], u: "1f514" },
    { n: ["no bell", "bell with cancellation stroke"], u: "1f515" },
    { n: ["musical score"], u: "1f3bc" },
    { n: ["musical note"], u: "1f3b5" },
    { n: ["notes", "multiple musical notes"], u: "1f3b6" },
    { n: ["studio microphone"], u: "1f399-fe0f" },
    { n: ["level slider"], u: "1f39a-fe0f" },
    { n: ["control knobs"], u: "1f39b-fe0f" },
    { n: ["microphone"], u: "1f3a4" },
    { n: ["headphone", "headphones"], u: "1f3a7" },
    { n: ["radio"], u: "1f4fb" },
    { n: ["saxophone"], u: "1f3b7" },
    { n: ["accordion"], u: "1fa97" },
    { n: ["guitar"], u: "1f3b8" },
    { n: ["musical keyboard"], u: "1f3b9" },
    { n: ["trumpet"], u: "1f3ba" },
    { n: ["violin"], u: "1f3bb" },
    { n: ["banjo"], u: "1fa95" },
    { n: ["drum with drumsticks"], u: "1f941" },
    { n: ["long drum"], u: "1fa98" },
    { n: ["iphone", "mobile phone"], u: "1f4f1" },
    {
      n: ["calling", "mobile phone with rightwards arrow at left"],
      u: "1f4f2",
    },
    { n: ["phone", "telephone", "black telephone"], u: "260e-fe0f" },
    { n: ["telephone receiver"], u: "1f4de" },
    { n: ["pager"], u: "1f4df" },
    { n: ["fax", "fax machine"], u: "1f4e0" },
    { n: ["battery"], u: "1f50b" },
    { n: ["low battery"], u: "1faab" },
    { n: ["electric plug"], u: "1f50c" },
    { n: ["computer", "personal computer"], u: "1f4bb" },
    { n: ["desktop computer"], u: "1f5a5-fe0f" },
    { n: ["printer"], u: "1f5a8-fe0f" },
    { n: ["keyboard"], u: "2328-fe0f" },
    { n: ["computer mouse", "three button mouse"], u: "1f5b1-fe0f" },
    { n: ["trackball"], u: "1f5b2-fe0f" },
    { n: ["minidisc"], u: "1f4bd" },
    { n: ["floppy disk"], u: "1f4be" },
    { n: ["cd", "optical disc"], u: "1f4bf" },
    { n: ["dvd"], u: "1f4c0" },
    { n: ["abacus"], u: "1f9ee" },
    { n: ["movie camera"], u: "1f3a5" },
    { n: ["film frames"], u: "1f39e-fe0f" },
    { n: ["film projector"], u: "1f4fd-fe0f" },
    { n: ["clapper", "clapper board"], u: "1f3ac" },
    { n: ["tv", "television"], u: "1f4fa" },
    { n: ["camera"], u: "1f4f7" },
    { n: ["camera with flash"], u: "1f4f8" },
    { n: ["video camera"], u: "1f4f9" },
    { n: ["vhs", "videocassette"], u: "1f4fc" },
    { n: ["mag", "left-pointing magnifying glass"], u: "1f50d" },
    { n: ["mag right", "right-pointing magnifying glass"], u: "1f50e" },
    { n: ["candle"], u: "1f56f-fe0f" },
    { n: ["bulb", "electric light bulb"], u: "1f4a1" },
    { n: ["flashlight", "electric torch"], u: "1f526" },
    { n: ["lantern", "izakaya lantern"], u: "1f3ee" },
    { n: ["diya lamp"], u: "1fa94" },
    { n: ["notebook with decorative cover"], u: "1f4d4" },
    { n: ["closed book"], u: "1f4d5" },
    { n: ["book", "open book"], u: "1f4d6" },
    { n: ["green book"], u: "1f4d7" },
    { n: ["blue book"], u: "1f4d8" },
    { n: ["orange book"], u: "1f4d9" },
    { n: ["books"], u: "1f4da" },
    { n: ["notebook"], u: "1f4d3" },
    { n: ["ledger"], u: "1f4d2" },
    { n: ["page with curl"], u: "1f4c3" },
    { n: ["scroll"], u: "1f4dc" },
    { n: ["page facing up"], u: "1f4c4" },
    { n: ["newspaper"], u: "1f4f0" },
    { n: ["rolled-up newspaper", "rolled up newspaper"], u: "1f5de-fe0f" },
    { n: ["bookmark tabs"], u: "1f4d1" },
    { n: ["bookmark"], u: "1f516" },
    { n: ["label"], u: "1f3f7-fe0f" },
    { n: ["moneybag", "money bag"], u: "1f4b0" },
    { n: ["coin"], u: "1fa99" },
    { n: ["yen", "banknote with yen sign"], u: "1f4b4" },
    { n: ["dollar", "banknote with dollar sign"], u: "1f4b5" },
    { n: ["euro", "banknote with euro sign"], u: "1f4b6" },
    { n: ["pound", "banknote with pound sign"], u: "1f4b7" },
    { n: ["money with wings"], u: "1f4b8" },
    { n: ["credit card"], u: "1f4b3" },
    { n: ["receipt"], u: "1f9fe" },
    { n: ["chart", "chart with upwards trend and yen sign"], u: "1f4b9" },
    { n: ["email", "envelope"], u: "2709-fe0f" },
    { n: ["e-mail", "e-mail symbol"], u: "1f4e7" },
    { n: ["incoming envelope"], u: "1f4e8" },
    {
      n: ["envelope with arrow", "envelope with downwards arrow above"],
      u: "1f4e9",
    },
    { n: ["outbox tray"], u: "1f4e4" },
    { n: ["inbox tray"], u: "1f4e5" },
    { n: ["package"], u: "1f4e6" },
    { n: ["mailbox", "closed mailbox with raised flag"], u: "1f4eb" },
    { n: ["mailbox closed", "closed mailbox with lowered flag"], u: "1f4ea" },
    { n: ["mailbox with mail", "open mailbox with raised flag"], u: "1f4ec" },
    {
      n: ["mailbox with no mail", "open mailbox with lowered flag"],
      u: "1f4ed",
    },
    { n: ["postbox"], u: "1f4ee" },
    { n: ["ballot box with ballot"], u: "1f5f3-fe0f" },
    { n: ["pencil", "pencil2"], u: "270f-fe0f" },
    { n: ["black nib"], u: "2712-fe0f" },
    { n: ["fountain pen", "lower left fountain pen"], u: "1f58b-fe0f" },
    { n: ["pen", "lower left ballpoint pen"], u: "1f58a-fe0f" },
    { n: ["paintbrush", "lower left paintbrush"], u: "1f58c-fe0f" },
    { n: ["crayon", "lower left crayon"], u: "1f58d-fe0f" },
    { n: ["memo", "pencil"], u: "1f4dd" },
    { n: ["briefcase"], u: "1f4bc" },
    { n: ["file folder"], u: "1f4c1" },
    { n: ["open file folder"], u: "1f4c2" },
    { n: ["card index dividers"], u: "1f5c2-fe0f" },
    { n: ["date", "calendar"], u: "1f4c5" },
    { n: ["calendar", "tear-off calendar"], u: "1f4c6" },
    { n: ["spiral notepad", "spiral note pad"], u: "1f5d2-fe0f" },
    { n: ["spiral calendar", "spiral calendar pad"], u: "1f5d3-fe0f" },
    { n: ["card index"], u: "1f4c7" },
    { n: ["chart with upwards trend"], u: "1f4c8" },
    { n: ["chart with downwards trend"], u: "1f4c9" },
    { n: ["bar chart"], u: "1f4ca" },
    { n: ["clipboard"], u: "1f4cb" },
    { n: ["pushpin"], u: "1f4cc" },
    { n: ["round pushpin"], u: "1f4cd" },
    { n: ["paperclip"], u: "1f4ce" },
    { n: ["linked paperclips"], u: "1f587-fe0f" },
    { n: ["straight ruler"], u: "1f4cf" },
    { n: ["triangular ruler"], u: "1f4d0" },
    { n: ["scissors", "black scissors"], u: "2702-fe0f" },
    { n: ["card file box"], u: "1f5c3-fe0f" },
    { n: ["file cabinet"], u: "1f5c4-fe0f" },
    { n: ["wastebasket"], u: "1f5d1-fe0f" },
    { n: ["lock"], u: "1f512" },
    { n: ["unlock", "open lock"], u: "1f513" },
    { n: ["lock with ink pen"], u: "1f50f" },
    { n: ["closed lock with key"], u: "1f510" },
    { n: ["key"], u: "1f511" },
    { n: ["old key"], u: "1f5dd-fe0f" },
    { n: ["hammer"], u: "1f528" },
    { n: ["axe"], u: "1fa93" },
    { n: ["pick"], u: "26cf-fe0f" },
    { n: ["hammer and pick"], u: "2692-fe0f" },
    { n: ["hammer and wrench"], u: "1f6e0-fe0f" },
    { n: ["dagger", "dagger knife"], u: "1f5e1-fe0f" },
    { n: ["crossed swords"], u: "2694-fe0f" },
    { n: ["gun", "pistol"], u: "1f52b" },
    { n: ["boomerang"], u: "1fa83" },
    { n: ["bow and arrow"], u: "1f3f9" },
    { n: ["shield"], u: "1f6e1-fe0f" },
    { n: ["carpentry saw"], u: "1fa9a" },
    { n: ["wrench"], u: "1f527" },
    { n: ["screwdriver"], u: "1fa9b" },
    { n: ["nut and bolt"], u: "1f529" },
    { n: ["gear"], u: "2699-fe0f" },
    { n: ["clamp", "compression"], u: "1f5dc-fe0f" },
    { n: ["scales", "balance scale"], u: "2696-fe0f" },
    { n: ["probing cane"], u: "1f9af" },
    { n: ["link", "link symbol"], u: "1f517" },
    { n: ["chains"], u: "26d3-fe0f" },
    { n: ["hook"], u: "1fa9d" },
    { n: ["toolbox"], u: "1f9f0" },
    { n: ["magnet"], u: "1f9f2" },
    { n: ["ladder"], u: "1fa9c" },
    { n: ["alembic"], u: "2697-fe0f" },
    { n: ["test tube"], u: "1f9ea" },
    { n: ["petri dish"], u: "1f9eb" },
    { n: ["dna", "dna double helix"], u: "1f9ec" },
    { n: ["microscope"], u: "1f52c" },
    { n: ["telescope"], u: "1f52d" },
    { n: ["satellite antenna"], u: "1f4e1" },
    { n: ["syringe"], u: "1f489" },
    { n: ["drop of blood"], u: "1fa78" },
    { n: ["pill"], u: "1f48a" },
    { n: ["adhesive bandage"], u: "1fa79" },
    { n: ["crutch"], u: "1fa7c" },
    { n: ["stethoscope"], u: "1fa7a" },
    { n: ["x-ray"], u: "1fa7b" },
    { n: ["door"], u: "1f6aa" },
    { n: ["elevator"], u: "1f6d7" },
    { n: ["mirror"], u: "1fa9e" },
    { n: ["window"], u: "1fa9f" },
    { n: ["bed"], u: "1f6cf-fe0f" },
    { n: ["couch and lamp"], u: "1f6cb-fe0f" },
    { n: ["chair"], u: "1fa91" },
    { n: ["toilet"], u: "1f6bd" },
    { n: ["plunger"], u: "1faa0" },
    { n: ["shower"], u: "1f6bf" },
    { n: ["bathtub"], u: "1f6c1" },
    { n: ["mouse trap"], u: "1faa4" },
    { n: ["razor"], u: "1fa92" },
    { n: ["lotion bottle"], u: "1f9f4" },
    { n: ["safety pin"], u: "1f9f7" },
    { n: ["broom"], u: "1f9f9" },
    { n: ["basket"], u: "1f9fa" },
    { n: ["roll of paper"], u: "1f9fb" },
    { n: ["bucket"], u: "1faa3" },
    { n: ["soap", "bar of soap"], u: "1f9fc" },
    { n: ["bubbles"], u: "1fae7" },
    { n: ["toothbrush"], u: "1faa5" },
    { n: ["sponge"], u: "1f9fd" },
    { n: ["fire extinguisher"], u: "1f9ef" },
    { n: ["shopping trolley"], u: "1f6d2" },
    { n: ["smoking", "smoking symbol"], u: "1f6ac" },
    { n: ["coffin"], u: "26b0-fe0f" },
    { n: ["headstone"], u: "1faa6" },
    { n: ["funeral urn"], u: "26b1-fe0f" },
    { n: ["moyai"], u: "1f5ff" },
    { n: ["placard"], u: "1faa7" },
    { n: ["identification card"], u: "1faaa" },
  ];
