import type { EmojiData } from "../../types/emojis";

export const symbols: EmojiData["symbols"] = [
  
    { n: ["atm", "automated teller machine"], u: "1f3e7" },
    {
      n: ["put litter in its place", "put litter in its place symbol"],
      u: "1f6ae",
    },
    { n: ["potable water", "potable water symbol"], u: "1f6b0" },
    { n: ["wheelchair", "wheelchair symbol"], u: "267f" },
    { n: ["mens", "mens symbol"], u: "1f6b9" },
    { n: ["womens", "womens symbol"], u: "1f6ba" },
    { n: ["restroom"], u: "1f6bb" },
    { n: ["baby symbol"], u: "1f6bc" },
    { n: ["wc", "water closet"], u: "1f6be" },
    { n: ["passport control"], u: "1f6c2" },
    { n: ["customs"], u: "1f6c3" },
    { n: ["baggage claim"], u: "1f6c4" },
    { n: ["left luggage"], u: "1f6c5" },
    { n: ["warning", "warning sign"], u: "26a0-fe0f" },
    { n: ["children crossing"], u: "1f6b8" },
    { n: ["no entry"], u: "26d4" },
    { n: ["no entry sign"], u: "1f6ab" },
    { n: ["no bicycles"], u: "1f6b3" },
    { n: ["no smoking", "no smoking symbol"], u: "1f6ad" },
    { n: ["do not litter", "do not litter symbol"], u: "1f6af" },
    { n: ["non-potable water", "non-potable water symbol"], u: "1f6b1" },
    { n: ["no pedestrians"], u: "1f6b7" },
    { n: ["no mobile phones"], u: "1f4f5" },
    { n: ["underage", "no one under eighteen symbol"], u: "1f51e" },
    { n: ["radioactive", "radioactive sign"], u: "2622-fe0f" },
    { n: ["biohazard", "biohazard sign"], u: "2623-fe0f" },
    { n: ["arrow up", "upwards black arrow"], u: "2b06-fe0f" },
    { n: ["north east arrow", "arrow upper right"], u: "2197-fe0f" },
    { n: ["arrow right", "black rightwards arrow"], u: "27a1-fe0f" },
    { n: ["south east arrow", "arrow lower right"], u: "2198-fe0f" },
    { n: ["arrow down", "downwards black arrow"], u: "2b07-fe0f" },
    { n: ["south west arrow", "arrow lower left"], u: "2199-fe0f" },
    { n: ["arrow left", "leftwards black arrow"], u: "2b05-fe0f" },
    { n: ["north west arrow", "arrow upper left"], u: "2196-fe0f" },
    { n: ["up down arrow", "arrow up down"], u: "2195-fe0f" },
    { n: ["left right arrow"], u: "2194-fe0f" },
    { n: ["leftwards arrow with hook"], u: "21a9-fe0f" },
    { n: ["arrow right hook", "rightwards arrow with hook"], u: "21aa-fe0f" },
    {
      n: ["arrow heading up", "arrow pointing rightwards then curving upwards"],
      u: "2934-fe0f",
    },
    {
      n: [
        "arrow heading down",
        "arrow pointing rightwards then curving downwards",
      ],
      u: "2935-fe0f",
    },
    {
      n: [
        "arrows clockwise",
        "clockwise downwards and upwards open circle arrows",
      ],
      u: "1f503",
    },
    {
      n: [
        "arrows counterclockwise",
        "anticlockwise downwards and upwards open circle arrows",
      ],
      u: "1f504",
    },
    { n: ["back", "back with leftwards arrow above"], u: "1f519" },
    { n: ["end", "end with leftwards arrow above"], u: "1f51a" },
    {
      n: ["on", "on with exclamation mark with left right arrow above"],
      u: "1f51b",
    },
    { n: ["soon", "soon with rightwards arrow above"], u: "1f51c" },
    { n: ["top", "top with upwards arrow above"], u: "1f51d" },
    { n: ["place of worship"], u: "1f6d0" },
    { n: ["atom symbol"], u: "269b-fe0f" },
    { n: ["om", "om symbol"], u: "1f549-fe0f" },
    { n: ["star of david"], u: "2721-fe0f" },
    { n: ["wheel of dharma"], u: "2638-fe0f" },
    { n: ["yin yang"], u: "262f-fe0f" },
    { n: ["latin cross"], u: "271d-fe0f" },
    { n: ["orthodox cross"], u: "2626-fe0f" },
    { n: ["star and crescent"], u: "262a-fe0f" },
    { n: ["peace symbol"], u: "262e-fe0f" },
    { n: ["menorah with nine branches"], u: "1f54e" },
    { n: ["six pointed star", "six pointed star with middle dot"], u: "1f52f" },
    { n: ["aries"], u: "2648" },
    { n: ["taurus"], u: "2649" },
    { n: ["gemini"], u: "264a" },
    { n: ["cancer"], u: "264b" },
    { n: ["leo"], u: "264c" },
    { n: ["virgo"], u: "264d" },
    { n: ["libra"], u: "264e" },
    { n: ["scorpius"], u: "264f" },
    { n: ["sagittarius"], u: "2650" },
    { n: ["capricorn"], u: "2651" },
    { n: ["aquarius"], u: "2652" },
    { n: ["pisces"], u: "2653" },
    { n: ["ophiuchus"], u: "26ce" },
    { n: ["twisted rightwards arrows"], u: "1f500" },
    {
      n: ["repeat", "clockwise rightwards and leftwards open circle arrows"],
      u: "1f501",
    },
    {
      n: [
        "repeat one",
        "clockwise rightwards and leftwards open circle arrows with circled one overlay",
      ],
      u: "1f502",
    },
    { n: ["arrow forward", "black right-pointing triangle"], u: "25b6-fe0f" },
    { n: ["fast forward", "black right-pointing double triangle"], u: "23e9" },
    {
      n: [
        "next track button",
        "black right pointing double triangle with vertical bar",
      ],
      u: "23ed-fe0f",
    },
    {
      n: [
        "play or pause button",
        "black right pointing triangle with double vertical bar",
      ],
      u: "23ef-fe0f",
    },
    { n: ["arrow backward", "black left-pointing triangle"], u: "25c0-fe0f" },
    { n: ["rewind", "black left-pointing double triangle"], u: "23ea" },
    {
      n: [
        "last track button",
        "black left pointing double triangle with vertical bar",
      ],
      u: "23ee-fe0f",
    },
    { n: ["arrow up small", "up-pointing small red triangle"], u: "1f53c" },
    { n: ["arrow double up", "black up-pointing double triangle"], u: "23eb" },
    { n: ["arrow down small", "down-pointing small red triangle"], u: "1f53d" },
    {
      n: ["arrow double down", "black down-pointing double triangle"],
      u: "23ec",
    },
    { n: ["pause button", "double vertical bar"], u: "23f8-fe0f" },
    { n: ["stop button", "black square for stop"], u: "23f9-fe0f" },
    { n: ["record button", "black circle for record"], u: "23fa-fe0f" },
    { n: ["eject", "eject button"], u: "23cf-fe0f" },
    { n: ["cinema"], u: "1f3a6" },
    { n: ["low brightness", "low brightness symbol"], u: "1f505" },
    { n: ["high brightness", "high brightness symbol"], u: "1f506" },
    { n: ["signal strength", "antenna with bars"], u: "1f4f6" },
    { n: ["vibration mode"], u: "1f4f3" },
    { n: ["mobile phone off"], u: "1f4f4" },
    { n: ["female sign"], u: "2640-fe0f" },
    { n: ["male sign"], u: "2642-fe0f" },
    { n: ["transgender symbol"], u: "26a7-fe0f" },
    { n: ["heavy multiplication x"], u: "2716-fe0f" },
    { n: ["heavy plus sign"], u: "2795" },
    { n: ["heavy minus sign"], u: "2796" },
    { n: ["heavy division sign"], u: "2797" },
    { n: ["heavy equals sign"], u: "1f7f0" },
    { n: ["infinity"], u: "267e-fe0f" },
    { n: ["bangbang", "double exclamation mark"], u: "203c-fe0f" },
    { n: ["interrobang", "exclamation question mark"], u: "2049-fe0f" },
    { n: ["question", "black question mark ornament"], u: "2753" },
    { n: ["grey question", "white question mark ornament"], u: "2754" },
    { n: ["grey exclamation", "white exclamation mark ornament"], u: "2755" },
    {
      n: [
        "exclamation",
        "heavy exclamation mark",
        "heavy exclamation mark symbol",
      ],
      u: "2757",
    },
    { n: ["wavy dash"], u: "3030-fe0f" },
    { n: ["currency exchange"], u: "1f4b1" },
    { n: ["heavy dollar sign"], u: "1f4b2" },
    { n: ["medical symbol", "staff of aesculapius"], u: "2695-fe0f" },
    { n: ["recycle", "black universal recycling symbol"], u: "267b-fe0f" },
    { n: ["fleur-de-lis", "fleur de lis"], u: "269c-fe0f" },
    { n: ["trident", "trident emblem"], u: "1f531" },
    { n: ["name badge"], u: "1f4db" },
    { n: ["beginner", "japanese symbol for beginner"], u: "1f530" },
    { n: ["o", "heavy large circle"], u: "2b55" },
    { n: ["white check mark", "white heavy check mark"], u: "2705" },
    { n: ["ballot box with check"], u: "2611-fe0f" },
    { n: ["heavy check mark"], u: "2714-fe0f" },
    { n: ["x", "cross mark"], u: "274c" },
    { n: ["negative squared cross mark"], u: "274e" },
    { n: ["curly loop"], u: "27b0" },
    { n: ["loop", "double curly loop"], u: "27bf" },
    { n: ["part alternation mark"], u: "303d-fe0f" },
    { n: ["eight spoked asterisk"], u: "2733-fe0f" },
    { n: ["eight pointed black star"], u: "2734-fe0f" },
    { n: ["sparkle"], u: "2747-fe0f" },
    { n: ["copyright", "copyright sign"], u: "00a9-fe0f" },
    { n: ["registered", "registered sign"], u: "00ae-fe0f" },
    { n: ["tm", "trade mark sign"], u: "2122-fe0f" },
    { n: ["hash", "hash key"], u: "0023-fe0f-20e3" },
    { n: ["keycap: *", "keycap star"], u: "002a-fe0f-20e3" },
    { n: ["zero", "keycap 0"], u: "0030-fe0f-20e3" },
    { n: ["one", "keycap 1"], u: "0031-fe0f-20e3" },
    { n: ["two", "keycap 2"], u: "0032-fe0f-20e3" },
    { n: ["three", "keycap 3"], u: "0033-fe0f-20e3" },
    { n: ["four", "keycap 4"], u: "0034-fe0f-20e3" },
    { n: ["five", "keycap 5"], u: "0035-fe0f-20e3" },
    { n: ["six", "keycap 6"], u: "0036-fe0f-20e3" },
    { n: ["seven", "keycap 7"], u: "0037-fe0f-20e3" },
    { n: ["eight", "keycap 8"], u: "0038-fe0f-20e3" },
    { n: ["nine", "keycap 9"], u: "0039-fe0f-20e3" },
    { n: ["keycap ten"], u: "1f51f" },
    {
      n: ["capital abcd", "input symbol for latin capital letters"],
      u: "1f520",
    },
    { n: ["abcd", "input symbol for latin small letters"], u: "1f521" },
    { n: ["1234", "input symbol for numbers"], u: "1f522" },
    { n: ["symbols", "input symbol for symbols"], u: "1f523" },
    { n: ["abc", "input symbol for latin letters"], u: "1f524" },
    { n: ["a", "negative squared latin capital letter a"], u: "1f170-fe0f" },
    { n: ["ab", "negative squared ab"], u: "1f18e" },
    { n: ["b", "negative squared latin capital letter b"], u: "1f171-fe0f" },
    { n: ["cl", "squared cl"], u: "1f191" },
    { n: ["cool", "squared cool"], u: "1f192" },
    { n: ["free", "squared free"], u: "1f193" },
    { n: ["information source"], u: "2139-fe0f" },
    { n: ["id", "squared id"], u: "1f194" },
    { n: ["m", "circled latin capital letter m"], u: "24c2-fe0f" },
    { n: ["new", "squared new"], u: "1f195" },
    { n: ["ng", "squared ng"], u: "1f196" },
    { n: ["o2", "negative squared latin capital letter o"], u: "1f17e-fe0f" },
    { n: ["ok", "squared ok"], u: "1f197" },
    {
      n: ["parking", "negative squared latin capital letter p"],
      u: "1f17f-fe0f",
    },
    { n: ["sos", "squared sos"], u: "1f198" },
    { n: ["up", "squared up with exclamation mark"], u: "1f199" },
    { n: ["vs", "squared vs"], u: "1f19a" },
    { n: ["koko", "squared katakana koko"], u: "1f201" },
    { n: ["sa", "squared katakana sa"], u: "1f202-fe0f" },
    { n: ["u6708", "squared cjk unified ideograph-6708"], u: "1f237-fe0f" },
    { n: ["u6709", "squared cjk unified ideograph-6709"], u: "1f236" },
    { n: ["u6307", "squared cjk unified ideograph-6307"], u: "1f22f" },
    { n: ["ideograph advantage", "circled ideograph advantage"], u: "1f250" },
    { n: ["u5272", "squared cjk unified ideograph-5272"], u: "1f239" },
    { n: ["u7121", "squared cjk unified ideograph-7121"], u: "1f21a" },
    { n: ["u7981", "squared cjk unified ideograph-7981"], u: "1f232" },
    { n: ["accept", "circled ideograph accept"], u: "1f251" },
    { n: ["u7533", "squared cjk unified ideograph-7533"], u: "1f238" },
    { n: ["u5408", "squared cjk unified ideograph-5408"], u: "1f234" },
    { n: ["u7a7a", "squared cjk unified ideograph-7a7a"], u: "1f233" },
    {
      n: ["congratulations", "circled ideograph congratulation"],
      u: "3297-fe0f",
    },
    { n: ["secret", "circled ideograph secret"], u: "3299-fe0f" },
    { n: ["u55b6", "squared cjk unified ideograph-55b6"], u: "1f23a" },
    { n: ["u6e80", "squared cjk unified ideograph-6e80"], u: "1f235" },
    { n: ["red circle", "large red circle"], u: "1f534" },
    { n: ["large orange circle"], u: "1f7e0" },
    { n: ["large yellow circle"], u: "1f7e1" },
    { n: ["large green circle"], u: "1f7e2" },
    { n: ["large blue circle"], u: "1f535" },
    { n: ["large purple circle"], u: "1f7e3" },
    { n: ["large brown circle"], u: "1f7e4" },
    { n: ["black circle", "medium black circle"], u: "26ab" },
    { n: ["white circle", "medium white circle"], u: "26aa" },
    { n: ["large red square"], u: "1f7e5" },
    { n: ["large orange square"], u: "1f7e7" },
    { n: ["large yellow square"], u: "1f7e8" },
    { n: ["large green square"], u: "1f7e9" },
    { n: ["large blue square"], u: "1f7e6" },
    { n: ["large purple square"], u: "1f7ea" },
    { n: ["large brown square"], u: "1f7eb" },
    { n: ["black large square"], u: "2b1b" },
    { n: ["white large square"], u: "2b1c" },
    { n: ["black medium square"], u: "25fc-fe0f" },
    { n: ["white medium square"], u: "25fb-fe0f" },
    { n: ["black medium small square"], u: "25fe" },
    { n: ["white medium small square"], u: "25fd" },
    { n: ["black small square"], u: "25aa-fe0f" },
    { n: ["white small square"], u: "25ab-fe0f" },
    { n: ["large orange diamond"], u: "1f536" },
    { n: ["large blue diamond"], u: "1f537" },
    { n: ["small orange diamond"], u: "1f538" },
    { n: ["small blue diamond"], u: "1f539" },
    { n: ["small red triangle", "up-pointing red triangle"], u: "1f53a" },
    {
      n: ["small red triangle down", "down-pointing red triangle"],
      u: "1f53b",
    },
    { n: ["diamond shape with a dot inside"], u: "1f4a0" },
    { n: ["radio button"], u: "1f518" },
    { n: ["white square button"], u: "1f533" },
    { n: ["black square button"], u: "1f532" },
  ],
];
