import type { EmojiData } from "../../types/emojis";

export const travel_places: EmojiData["travel_places"] = [
  
    { n: ["earth africa", "earth globe europe-africa"], u: "1f30d" },
    { n: ["earth americas", "earth globe americas"], u: "1f30e" },
    { n: ["earth asia", "earth globe asia-australia"], u: "1f30f" },
    { n: ["globe with meridians"], u: "1f310" },
    { n: ["world map"], u: "1f5fa-fe0f" },
    { n: ["japan", "silhouette of japan"], u: "1f5fe" },
    { n: ["compass"], u: "1f9ed" },
    { n: ["snow-capped mountain", "snow capped mountain"], u: "1f3d4-fe0f" },
    { n: ["mountain"], u: "26f0-fe0f" },
    { n: ["volcano"], u: "1f30b" },
    { n: ["mount fuji"], u: "1f5fb" },
    { n: ["camping"], u: "1f3d5-fe0f" },
    { n: ["beach with umbrella"], u: "1f3d6-fe0f" },
    { n: ["desert"], u: "1f3dc-fe0f" },
    { n: ["desert island"], u: "1f3dd-fe0f" },
    { n: ["national park"], u: "1f3de-fe0f" },
    { n: ["stadium"], u: "1f3df-fe0f" },
    { n: ["classical building"], u: "1f3db-fe0f" },
    { n: ["building construction"], u: "1f3d7-fe0f" },
    { n: ["brick", "bricks"], u: "1f9f1" },
    { n: ["rock"], u: "1faa8" },
    { n: ["wood"], u: "1fab5" },
    { n: ["hut"], u: "1f6d6" },
    { n: ["houses", "house buildings"], u: "1f3d8-fe0f" },
    { n: ["derelict house", "derelict house building"], u: "1f3da-fe0f" },
    { n: ["house", "house building"], u: "1f3e0" },
    { n: ["house with garden"], u: "1f3e1" },
    { n: ["office", "office building"], u: "1f3e2" },
    { n: ["post office", "japanese post office"], u: "1f3e3" },
    { n: ["european post office"], u: "1f3e4" },
    { n: ["hospital"], u: "1f3e5" },
    { n: ["bank"], u: "1f3e6" },
    { n: ["hotel"], u: "1f3e8" },
    { n: ["love hotel"], u: "1f3e9" },
    { n: ["convenience store"], u: "1f3ea" },
    { n: ["school"], u: "1f3eb" },
    { n: ["department store"], u: "1f3ec" },
    { n: ["factory"], u: "1f3ed" },
    { n: ["japanese castle"], u: "1f3ef" },
    { n: ["european castle"], u: "1f3f0" },
    { n: ["wedding"], u: "1f492" },
    { n: ["tokyo tower"], u: "1f5fc" },
    { n: ["statue of liberty"], u: "1f5fd" },
    { n: ["church"], u: "26ea" },
    { n: ["mosque"], u: "1f54c" },
    { n: ["hindu temple"], u: "1f6d5" },
    { n: ["synagogue"], u: "1f54d" },
    { n: ["shinto shrine"], u: "26e9-fe0f" },
    { n: ["kaaba"], u: "1f54b" },
    { n: ["fountain"], u: "26f2" },
    { n: ["tent"], u: "26fa" },
    { n: ["foggy"], u: "1f301" },
    { n: ["night with stars"], u: "1f303" },
    { n: ["cityscape"], u: "1f3d9-fe0f" },
    { n: ["sunrise over mountains"], u: "1f304" },
    { n: ["sunrise"], u: "1f305" },
    { n: ["city sunset", "cityscape at dusk"], u: "1f306" },
    { n: ["city sunrise", "sunset over buildings"], u: "1f307" },
    { n: ["bridge at night"], u: "1f309" },
    { n: ["hotsprings", "hot springs"], u: "2668-fe0f" },
    { n: ["carousel horse"], u: "1f3a0" },
    { n: ["playground slide"], u: "1f6dd" },
    { n: ["ferris wheel"], u: "1f3a1" },
    { n: ["roller coaster"], u: "1f3a2" },
    { n: ["barber", "barber pole"], u: "1f488" },
    { n: ["circus tent"], u: "1f3aa" },
    { n: ["steam locomotive"], u: "1f682" },
    { n: ["railway car"], u: "1f683" },
    { n: ["high-speed train", "bullettrain side"], u: "1f684" },
    {
      n: ["bullettrain front", "high-speed train with bullet nose"],
      u: "1f685",
    },
    { n: ["train", "train2"], u: "1f686" },
    { n: ["metro"], u: "1f687" },
    { n: ["light rail"], u: "1f688" },
    { n: ["station"], u: "1f689" },
    { n: ["tram"], u: "1f68a" },
    { n: ["monorail"], u: "1f69d" },
    { n: ["mountain railway"], u: "1f69e" },
    { n: ["train", "tram car"], u: "1f68b" },
    { n: ["bus"], u: "1f68c" },
    { n: ["oncoming bus"], u: "1f68d" },
    { n: ["trolleybus"], u: "1f68e" },
    { n: ["minibus"], u: "1f690" },
    { n: ["ambulance"], u: "1f691" },
    { n: ["fire engine"], u: "1f692" },
    { n: ["police car"], u: "1f693" },
    { n: ["oncoming police car"], u: "1f694" },
    { n: ["taxi"], u: "1f695" },
    { n: ["oncoming taxi"], u: "1f696" },
    { n: ["car", "red car", "automobile"], u: "1f697" },
    { n: ["oncoming automobile"], u: "1f698" },
    { n: ["blue car", "recreational vehicle"], u: "1f699" },
    { n: ["pickup truck"], u: "1f6fb" },
    { n: ["truck", "delivery truck"], u: "1f69a" },
    { n: ["articulated lorry"], u: "1f69b" },
    { n: ["tractor"], u: "1f69c" },
    { n: ["racing car"], u: "1f3ce-fe0f" },
    { n: ["motorcycle", "racing motorcycle"], u: "1f3cd-fe0f" },
    { n: ["motor scooter"], u: "1f6f5" },
    { n: ["manual wheelchair"], u: "1f9bd" },
    { n: ["motorized wheelchair"], u: "1f9bc" },
    { n: ["auto rickshaw"], u: "1f6fa" },
    { n: ["bike", "bicycle"], u: "1f6b2" },
    { n: ["scooter"], u: "1f6f4" },
    { n: ["skateboard"], u: "1f6f9" },
    { n: ["roller skate"], u: "1f6fc" },
    { n: ["busstop", "bus stop"], u: "1f68f" },
    { n: ["motorway"], u: "1f6e3-fe0f" },
    { n: ["railway track"], u: "1f6e4-fe0f" },
    { n: ["oil drum"], u: "1f6e2-fe0f" },
    { n: ["fuelpump", "fuel pump"], u: "26fd" },
    { n: ["wheel"], u: "1f6de" },
    { n: ["rotating light", "police cars revolving light"], u: "1f6a8" },
    { n: ["traffic light", "horizontal traffic light"], u: "1f6a5" },
    { n: ["vertical traffic light"], u: "1f6a6" },
    { n: ["octagonal sign"], u: "1f6d1" },
    { n: ["construction", "construction sign"], u: "1f6a7" },
    { n: ["anchor"], u: "2693" },
    { n: ["ring buoy"], u: "1f6df" },
    { n: ["boat", "sailboat"], u: "26f5" },
    { n: ["canoe"], u: "1f6f6" },
    { n: ["speedboat"], u: "1f6a4" },
    { n: ["passenger ship"], u: "1f6f3-fe0f" },
    { n: ["ferry"], u: "26f4-fe0f" },
    { n: ["motor boat"], u: "1f6e5-fe0f" },
    { n: ["ship"], u: "1f6a2" },
    { n: ["airplane"], u: "2708-fe0f" },
    { n: ["small airplane"], u: "1f6e9-fe0f" },
    { n: ["airplane departure"], u: "1f6eb" },
    { n: ["airplane arriving"], u: "1f6ec" },
    { n: ["parachute"], u: "1fa82" },
    { n: ["seat"], u: "1f4ba" },
    { n: ["helicopter"], u: "1f681" },
    { n: ["suspension railway"], u: "1f69f" },
    { n: ["mountain cableway"], u: "1f6a0" },
    { n: ["aerial tramway"], u: "1f6a1" },
    { n: ["satellite"], u: "1f6f0-fe0f" },
    { n: ["rocket"], u: "1f680" },
    { n: ["flying saucer"], u: "1f6f8" },
    { n: ["bellhop bell"], u: "1f6ce-fe0f" },
    { n: ["luggage"], u: "1f9f3" },
    { n: ["hourglass"], u: "231b" },
    { n: ["hourglass flowing sand", "hourglass with flowing sand"], u: "23f3" },
    { n: ["watch"], u: "231a" },
    { n: ["alarm clock"], u: "23f0" },
    { n: ["stopwatch"], u: "23f1-fe0f" },
    { n: ["timer clock"], u: "23f2-fe0f" },
    { n: ["mantelpiece clock"], u: "1f570-fe0f" },
    { n: ["clock12", "clock face twelve oclock"], u: "1f55b" },
    { n: ["clock1230", "clock face twelve-thirty"], u: "1f567" },
    { n: ["clock1", "clock face one oclock"], u: "1f550" },
    { n: ["clock130", "clock face one-thirty"], u: "1f55c" },
    { n: ["clock2", "clock face two oclock"], u: "1f551" },
    { n: ["clock230", "clock face two-thirty"], u: "1f55d" },
    { n: ["clock3", "clock face three oclock"], u: "1f552" },
    { n: ["clock330", "clock face three-thirty"], u: "1f55e" },
    { n: ["clock4", "clock face four oclock"], u: "1f553" },
    { n: ["clock430", "clock face four-thirty"], u: "1f55f" },
    { n: ["clock5", "clock face five oclock"], u: "1f554" },
    { n: ["clock530", "clock face five-thirty"], u: "1f560" },
    { n: ["clock6", "clock face six oclock"], u: "1f555" },
    { n: ["clock630", "clock face six-thirty"], u: "1f561" },
    { n: ["clock7", "clock face seven oclock"], u: "1f556" },
    { n: ["clock730", "clock face seven-thirty"], u: "1f562" },
    { n: ["clock8", "clock face eight oclock"], u: "1f557" },
    { n: ["clock830", "clock face eight-thirty"], u: "1f563" },
    { n: ["clock9", "clock face nine oclock"], u: "1f558" },
    { n: ["clock930", "clock face nine-thirty"], u: "1f564" },
    { n: ["clock10", "clock face ten oclock"], u: "1f559" },
    { n: ["clock1030", "clock face ten-thirty"], u: "1f565" },
    { n: ["clock11", "clock face eleven oclock"], u: "1f55a" },
    { n: ["clock1130", "clock face eleven-thirty"], u: "1f566" },
    { n: ["new moon", "new moon symbol"], u: "1f311" },
    { n: ["waxing crescent moon", "waxing crescent moon symbol"], u: "1f312" },
    { n: ["first quarter moon", "first quarter moon symbol"], u: "1f313" },
    {
      n: ["moon", "waxing gibbous moon", "waxing gibbous moon symbol"],
      u: "1f314",
    },
    { n: ["full moon", "full moon symbol"], u: "1f315" },
    { n: ["waning gibbous moon", "waning gibbous moon symbol"], u: "1f316" },
    { n: ["last quarter moon", "last quarter moon symbol"], u: "1f317" },
    { n: ["waning crescent moon", "waning crescent moon symbol"], u: "1f318" },
    { n: ["crescent moon"], u: "1f319" },
    { n: ["new moon with face"], u: "1f31a" },
    { n: ["first quarter moon with face"], u: "1f31b" },
    { n: ["last quarter moon with face"], u: "1f31c" },
    { n: ["thermometer"], u: "1f321-fe0f" },
    { n: ["sunny", "black sun with rays"], u: "2600-fe0f" },
    { n: ["full moon with face"], u: "1f31d" },
    { n: ["sun with face"], u: "1f31e" },
    { n: ["ringed planet"], u: "1fa90" },
    { n: ["star", "white medium star"], u: "2b50" },
    { n: ["star2", "glowing star"], u: "1f31f" },
    { n: ["stars", "shooting star"], u: "1f320" },
    { n: ["milky way"], u: "1f30c" },
    { n: ["cloud"], u: "2601-fe0f" },
    { n: ["partly sunny", "sun behind cloud"], u: "26c5" },
    {
      n: ["thunder cloud and rain", "cloud with lightning and rain"],
      u: "26c8-fe0f",
    },
    {
      n: ["mostly sunny", "sun small cloud", "sun behind small cloud"],
      u: "1f324-fe0f",
    },
    {
      n: ["barely sunny", "sun behind cloud", "sun behind large cloud"],
      u: "1f325-fe0f",
    },
    { n: ["partly sunny rain", "sun behind rain cloud"], u: "1f326-fe0f" },
    { n: ["rain cloud", "cloud with rain"], u: "1f327-fe0f" },
    { n: ["snow cloud", "cloud with snow"], u: "1f328-fe0f" },
    {
      n: ["lightning", "lightning cloud", "cloud with lightning"],
      u: "1f329-fe0f",
    },
    { n: ["tornado", "tornado cloud"], u: "1f32a-fe0f" },
    { n: ["fog"], u: "1f32b-fe0f" },
    { n: ["wind face", "wind blowing face"], u: "1f32c-fe0f" },
    { n: ["cyclone"], u: "1f300" },
    { n: ["rainbow"], u: "1f308" },
    { n: ["closed umbrella"], u: "1f302" },
    { n: ["umbrella"], u: "2602-fe0f" },
    { n: ["umbrella with rain drops"], u: "2614" },
    { n: ["umbrella on ground"], u: "26f1-fe0f" },
    { n: ["zap", "high voltage sign"], u: "26a1" },
    { n: ["snowflake"], u: "2744-fe0f" },
    { n: ["snowman"], u: "2603-fe0f" },
    { n: ["snowman without snow"], u: "26c4" },
    { n: ["comet"], u: "2604-fe0f" },
    { n: ["fire"], u: "1f525" },
    { n: ["droplet"], u: "1f4a7" },
    { n: ["ocean", "water wave"], u: "1f30a" },
  ],
};
