import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const packageJsonPath = join(process.cwd(), 'package.json');
const manifestJsonPath = join(process.cwd(), 'manifest.json');
const versionTsPath = join(process.cwd(), 'src', 'version.ts');

try {
  // 1. Read package.json version
  if (!existsSync(packageJsonPath)) {
    console.error('Error: package.json not found in the current working directory.');
    process.exit(1);
  }
  const packageJson = JSON.parse(readFileSync(packageJsonPath, 'utf8'));
  const version = packageJson.version;

  if (!version) {
    console.error('Error: "version" field not found in package.json.');
    process.exit(1);
  }

  // 2. Read and update manifest.json version
  if (existsSync(manifestJsonPath)) {
    const manifestJson = JSON.parse(readFileSync(manifestJsonPath, 'utf8'));
    if (manifestJson.version !== version) {
      manifestJson.version = version;
      writeFileSync(manifestJsonPath, JSON.stringify(manifestJson, null, 2) + '\n');
      console.log(`Updated manifest.json version to ${version}`);
    } else {
      console.log(`manifest.json version is already in sync (${version})`);
    }
  } else {
    console.warn('Warning: manifest.json not found. Skipping version sync for manifest.json.');
  }

  // 3. Update src/version.ts
  const newVersionTsContent = `// This file is auto-generated by scripts/sync-version.mjs
// Do not edit manually - update version in package.json instead
export const VERSION = "${version}";
`;

  let updateVersionTs = true;
  if (existsSync(versionTsPath)) {
    const currentContent = readFileSync(versionTsPath, 'utf8');
    if (currentContent.trim() === newVersionTsContent.trim()) {
      updateVersionTs = false;
    }
  }

  if (updateVersionTs) {
    writeFileSync(versionTsPath, newVersionTsContent);
    console.log(`Updated src/version.ts with version ${version}`);
  } else {
    console.log(`src/version.ts version is already in sync (${version})`);
  }

} catch (error) {
  console.error('Failed to sync version:', error);
  process.exit(1);
}
